# Práctica 1 - Self-Organising Maps
## Preparación de entorno
#### Importar librerías de código

In [65]:
%reset
# from __future__ import division
import math
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import patches as patches

%matplotlib inline

#### Dataset que se va a utilizar para el entrenamiento

In [66]:
# Código para obtener el Dataset que se va a usar en el entrenamiento
datos = np.random.randint(0, 255, (100, 3))

## SOM Setup
#### Variables definidas por el alumno

In [67]:
# Inicializa tamaño del mapa de Kohonen, número de iteraciones y learning rate
# Inicializa normalizar_datos dependiendo de si tienes que normalizar los datos o no
lado_mapa = 10
periodo = 100
learning_rate = 0.1
normalizar_datos = True

#### A partir de este punto solo hay cálculos. No se introducen más valores "a mano"

In [ ]:
# Normaliza los datos si fuese necesario dividiendo cada dato por el máximo en la matriz
if normalizar_datos:
    datos = datos/255

# Establece el numero de entradas del mapa y el número de datos que se van a usar para entrenar. 
# Utiliza una función que obtenga automáticamente los valores a partir del Dataset.
 
def patron_escogido(datos):
    valor = np.random.randint(0, 100)
    patron_elegido = datos[valor]
    num_entradas = patron_elegido.size
    return patron_elegido, num_entradas


# Calcula el vecindario inicial. Debe ser la mitad del lado del mapa de Kohonen
vecindario = lado_mapa // 2



    
# Crea una matriz de pesos con valores random entre 0 y 1. Usa la función random.random de la librería NumPy
#matriz_pesos = np.random.random((dimensiones de la matriz de pesos))
matriz_pesos = np.random.random((lado_mapa, lado_mapa, num_entradas))
print(matriz_pesos[0,0])


El patron elegido es  [0.6        0.53333333 0.98823529]  y el numero de entradas es  3
[0.25051386 0.06834251 0.21908217]


#### Funciones para entrenar/clasificar

In [ ]:
# Función para encontrar la BMU
"""
   Encuentra la BMU para un patrón de entrada.
   Entradas: (patrón_de_entrada, matriz_de_pesos, número_de_entradas)
   Salidas:  (bmu, bmu_idx) tupla donde
               bmu: vector de pesos de la neurona ganadora
               bum_idx: coordenadas de la neurona ganadora
"""
def calcular_bmu(patron_entrada, m_pesos, m):
    distancia_max = -1
    bmu_index = [-1, -1]
    bmu = [-1, -1, -1]
    for i in range(lado_mapa):
        for j in range(lado_mapa):
            distancia_euclidea = math.sqrt((patron_entrada[0] - m_pesos[i,j][0])**2 + (patron_entrada[1] - m_pesos[i,j][1])**2 + (patron_entrada[2] - m_pesos[i,j][2])**2)
            if distancia_euclidea > distancia_max :
                distancia_max = distancia_euclidea
                bmu_index = [i, j]
                bmu = m_pesos[i,j]
    print(bmu, bmu_index, distancia_max)
    return bmu, bmu_index



[0.06157332 0.30169476 0.00820356] [7, 6] 1.1419377955823304


(array([0.06157332, 0.30169476, 0.00820356]), [7, 6])

In [71]:
# Función para calcular el descenso del coeficiente de aprendizaje (eta)
"""
   Calcula el Learning Rate (eta) que corresponde a la i-ésima presentación.
   Entradas: (learning_rate_inicial, iteracion, período)
   Salidas:  learning_rate para la iteración i

"""
def variacion_learning_rate(lr_inicial, i, n_iteraciones):
    learning_rate = lr_inicial * (1 - (i//n_iteraciones))
    return learning_rate


In [ ]:
# Función para calcular el descenso del vecindario (v)
"""
   Calcula el vecindario  (v) que corresponde a la i-ésima presentación.
   Entradas: (vecindario_inicial, iteracion, período)
   Salidas:  lvecindario para la iteración i

"""
def variacion_vecindario(vecindario_inicial, i, n_iteraciones):
    vecindario_actual = 1 + (vecindario_inicial * (1 - i/n_iteraciones))
    return vecindario_actual

In [ ]:
# Función para calcular el descenso del coeficiente de aprendizaje (eta) en función de la distancia a la BMU
"""
   Calcula la amortiguación de eta en función de la distancia en el mapa entre una neurona y la BMU.
   Entradas: (distancia_BMU, vecindario_actual)
   Salidas:  amortiguación para la iteración

"""
def decay(distancia_BMU, vecindario_actual):
    return np.exp(-distancia_BMU / (2* (vecindario_actual**2)))


#### Funciones para dibujar la salida de la red

In [ ]:
# Función para pintar una matriz de valores como colores RGB
def pintar_mapa(matriz_valores):
    fig = plt.figure()
    
    # Establece ejes
    ax = fig.add_subplot(111, aspect='equal')
    ax.set_xlim((0, matriz_pesos.shape[0]+1))
    ax.set_ylim((0, matriz_pesos.shape[1]+1))
    ax.set_title('Self-Organising Map después de %d iteraciones' % periodo)

    # Dibuja los rectángulos de color RGB
    for x in range(1, matriz_valores.shape[0] + 1):
        for y in range(1, matriz_valores.shape[1] + 1):
            ax.add_patch(patches.Rectangle((x-0.5, y-0.5), 1, 1,
                         facecolor=matriz_valores[x-1,y-1,:],
                         edgecolor='none'))
    plt.show()

## SOM Entrenamiento

In [ ]:
# Entrena la red con el dataset de entrenamiento


## SOM Clasificación

In [ ]:
# Clasifica los patrones de entrenamiento con la matriz de pesos recién entrenada



## SOM Prueba

In [ ]:
# Clasifica nuevos patrones

